### ISSUE TITLE
Method of checking if a user is an admin

### ISSUE THREAD

**Issue by finnbear** [fixmyrights/discord-bot#10]
Maybe use a special role?

**Comment by j1mbl3s** [comment]
Following from https://github.com/fixmyrights/discord-bot/issues/16, would it make sense for someone who has permission to manage a channel to manage the bot in that channel?

Given `message` as a [`Message`](https://discord.js.org/#/docs/main/stable/class/Message) and assuming that we're operating in a [`TextChannel`](https://discord.js.org/#/docs/main/stable/class/TextChannel)
```
const { Permisions } = require('discord.js');
...
if ((message.channel.memberPermissions(message.author) || {has: () => false})
      .has(Permissions.FLAGS.MANAGE_CHANNELS)) {
    // do cool stuff
}
```
I haven't tested this, but in theory it should work. I would test that using the `MANAGE_CHANNELS` flag works when that channel is the only one the user has permission to manage, though.

Check out the [`Permissions.FLAGS`](https://discord.js.org/#/docs/main/stable/class/Permissions?scrollTo=s-FLAGS) documentation.

**Comment by finnbear** [comment]
We could also treat anyone who has the permissions to chat in the dedicated channel as an admin for our purposes.

**Comment by j1mbl3s** [comment]
A server administrator could set the roles that can interact with the bot, saved in the config. Then both administrators and those roles can interact with the bot. Or maybe I am missing the intention of finding permissions/roles?

**Comment by ghost** [comment]
A simple solution will be to add guild owners and a bunch of developer ids (from configuration or an env var) to the bot as administrators. While this solution isn't perfect it might be enough for an MVP.

**Comment by finnbear** [comment]
Anything wrong with only allowing those in the configured channel to use it? It is very simple and has the benefit of reducing clutter in that channel. Since no one else can chat there, the bill reports wont get buried.

**Comment by akuinu** [comment]
One question that needs to be answered:
Is bot instance meant to run on only one discord guild or multiple?
With my quick cleanse on the current code it seems it would be designed with one bot instance with its DB serving one(maybe changing as it seems no db yet decided #13  )
If one instance system then env variables for allowing users would be fine

But in my opinion owner and/or administrator to configurable role based system is better - once bot is invited to the guild somebody can configure who can interact with bot and in which channel bot will message/respond

**Comment by finnbear** [comment]
I haven't really decided whether a single instance of a bot should be able to satisfy multiple guilds/servers.

**Comment by akuinu** [comment]
Well for MVP the 
```js
if (msg.member.hasPermission("ADMINISTRATOR")) {
    // do the things
}
```
should be enough, unless there are no person with admin rights among people that build this

**Comment by j1mbl3s** [comment]
If checking, say, from a DM to the bot with an argument of `<guild id>`:
```
Client.guilds.get(<guild id>)
  .members.get(<message author id>)
  .permissions.has(Permissions.FLAGS.ADMINISTRATOR)
```

**Comment by joaodforce** [comment]
#44
