### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by ChadBailey** [fixmyrights/discord-bot#14]
I don't know what this project should be called, but I don't think it should be "discord-bot", as i'm [pretty sure](https://github.com/search?q=discord-bot) the name has been taken already.

What is the group's thoughts for a better name?

**Comment by joaodforce** [comment]
This is an interesting topic, because at first the BOT was called `Blackberry` paying homage to the current bots on Loui's server, but when we shifted the codebase from RUST to JavaScript it got lost, I guess we can create a pool for the name? Or just change it back.

**Comment by finnbear** [comment]
There is no reason the bot has to have the same name as the repo, in fact I never intended for it to have the repo's name.

**Comment by finnbear** [comment]
Blackberry is fine with me.

**Comment by ghost** [comment]
`blackberry-bot` is distinctive enough.

**Comment by joaodforce** [comment]
> There is no reason the bot has to have the same name as the repo, in fact I never intended for it to have the repo's name.

indeed, but it should be more distinctive in case we need to make another bot for example, this makes the organisation's repository naming scheme better.

**Comment by finnbear** [comment]
but what if we wanted to make a bot that did the same thing, but for slack?

Equally hypothetical but leads to opposite conclusion that the current name is good.

**Comment by joaodforce** [comment]
> what if we wanted to make a b

this conversation can go on forever, but fun fact at my company we put the technology/language of the project as part of the repo name. we could call it blackberry-bot-js But still. Lets not focus too much on these details.

**Comment by ghost** [comment]
I'm closing this since will not rename this repo or project for now.
The bot name will probably be `Blackberry kitty` to follow what me already have with Mr Clinton.

**Comment by j1mbl3s** [comment]
I know this is closed, but I'll throw in my two cents: `legibot`, `legibot-discord`, or some variant. It's up to how the bot is configured through the Discord Developer Portal what a specific instance of the bot is named, and I think this suggestion is pretty instance agnostic naming while still capturing the purpose of the project.
