### ISSUE TITLE
Keep LegiScan column syntax like last_action_date or use lastActionDate

### ISSUE THREAD

**Issue by finnbear** [fixmyrights/discord-bot#26]
When we read in the data, should we make the column names more native to javascript and our coding style?

**Comment by asheliahut** [comment]
Base rule of thumb to live by atleast for myself and many others I know. If it is a variable or a representation in code use camelCase

If it is a database or data name snake_case

If it is a class name in PascalCase

**Comment by finnbear** [comment]
> Base rule of thumb to live by atleast for myself and many others I know. If it is a variable or a representation in code use camelCase
> 
> If it is a database or data name snake_case

Given that the database is a JSON file, read directly into memory, it makes sense to use the same naming scheme in the DB and in the code. The question is whether that scheme should match legiscan's or our own. I think I prefer converting to camel case as soon as the data is received by the api.

**Comment by finnbear** [comment]
Will convert to camel case.

**Comment by asheliahut** [comment]
Yeah as soon as data is in code it should be camel just as you have done.
