### ISSUE TITLE
How should the bot format responses, bills, and lists of bills?

### ISSUE THREAD

**Issue by finnbear** [fixmyrights/discord-bot#33]
Questions
- Should discord embeds be used? How? #32 
- Should more than one line per bill be used?

Types of formats (images are what the current format is)
- List of bills
![image](https://user-images.githubusercontent.com/20015102/73604252-479f4600-4542-11ea-9e20-791cbf1d6681.png)
- Bill new notification
![image](https://user-images.githubusercontent.com/20015102/73604240-0e66d600-4542-11ea-8c87-4be537127d0e.png)
- Bill change notification
![image](https://user-images.githubusercontent.com/20015102/73604238-ff802380-4541-11ea-87e4-15cb5168c80b.png)

**Comment by finnbear** [comment]
Sample data for bill
```
"1162946": {
      "state": "HI",
      "number": "SB425",
      "title": "Relating To Fair Digital Electronic Equipment Repair.",
      "url": "https://legiscan.com/HI/bill/SB425/2019",
      "history": [
        {
          "action": "The committee on TEC deferred the measure.",
          "timestamp": 1548892800000
        },
        {
          "action": "Introduced.",
          "timestamp": 1547769600000
        },
        {
          "action": "Passed First Reading.",
          "timestamp": 1548115200000
        },
        {
          "action": "Referred to TEC, CPH.",
          "timestamp": 1548288000000
        },
        {
          "action": "The committee(s) on TEC has scheduled a public hearing on 01-31-19 2:45PM in conference room 414.",
          "timestamp": 1548633600000
        }
      ],
      "watching": true,
      "calendar": [
        {
          "type": "Hearing",
          "description": "Senate Technology and the Arts Hearing",
          "localDate": "2019-01-31",
          "localTime": "14:45",
          "location": "Conference Room 414",
          "timestamp": 1548981900000
        },
        {
          "type": "Hearing",
          "description": "Senate Hearing (not real)",
          "localDate": "2019-02-21",
          "localTime": "12:45",
          "location": "Conference Room 9000",
          "timestamp": XXXXXXXXXXX
        }
      ]
    }
```

**Comment by asheliahut** [comment]
Using rich embeds with pagination. Discussed with @finnbear about having 5 per page with a show more option. PR: https://github.com/fixmyrights/discord-bot/pull/37

With Out Show More
<img width="291" alt="WithoutShowMore" src="https://user-images.githubusercontent.com/945619/73622829-78898480-45ef-11ea-91a8-5b4800c602b8.png">

With Show More
<img width="321" alt="WithShowMore" src="https://user-images.githubusercontent.com/945619/73622843-850ddd00-45ef-11ea-8291-6f631d96bfb9.png">

After Show More Pressed
<img width="313" alt="AfterShowMorePressed" src="https://user-images.githubusercontent.com/945619/73622853-8ccd8180-45ef-11ea-9cb3-2645b5991d8d.png">
