### ISSUE TITLE
Display a summary if imminent hearings

### ISSUE THREAD

**Issue by finnbear** [fixmyrights/discord-bot#40]
There should be a command, under `bill`, to display a summary of hearings in the near future for all watched bills. Alternatively, this message could be automated. Alternatively, it could be both automated and manually accessible.

Extras:
- Display distance to hearing from a defined location

**Comment by j1mbl3s** [comment]
If using the automated method, there should be a config command to set the alert schedule for imminent hearings (e.g. hour before, 2 hours before, etc). A cron job could be scheduled for bills with a defined hearing and kept in a list to update the job as necessary.
