### ISSUE TITLE
Commands crash bot

### ISSUE THREAD

**Issue by akuinu** [fixmyrights/discord-bot#50]
Unfinished commands `!bill` and `!config` will crash the bot.
String operation attempted on `underfined`

**Comment by akuinu** [comment]
my fix would be 

```JS
  const arg = args.shift();
  if (!arg){
    help.handle(args, message, client);
    return;
  }
   const handler = arg.toLowerCase();
```
instead of:
https://github.com/fixmyrights/discord-bot/blob/56a8ba4b11d96e00e08601549e7f317c8c3fb569/src/commands/config/handler.js#L30
https://github.com/fixmyrights/discord-bot/blob/56a8ba4b11d96e00e08601549e7f317c8c3fb569/src/commands/bill/handler.js#L29

**Comment by finnbear** [comment]
I requested a change on your PR but this is a good thing to fix.
