### ISSUE TITLE
Allow polling for changes within past time period by storing incremental updates

### ISSUE THREAD

**Issue by yasamoka** [fixmyrights/discord-bot#7]
Say a person of concern is too busy to scroll through the list of periodic (hourly, quarter-daily, daily) updates.

Store incremental updates and allow messages to request a period of time, e.g. the changes within the last 48h.

The incremental changes are stored into the database by 1) checking if change_hash has changed every polling interval and 2) adding new bills as if this is the first update to that bill.

When requested, apply the incremental updates from the start of the chosen time period till the end on all the bills that have received updates or have appeared within the specified time period.

If implemented in a more generalized manner, this could also be used for gathering statistics over time regarding new and updated bills.

**Comment by finnbear** [comment]
We now support reminders which keep appearing when a hearing is imminent.
